"""Read/write the ``.mu`` files a hosted NomadNet node serves.

Backs the Reticulum page's **Pages** tab -- an in-dashboard editor for the
Micron pages under ``plugins.reticulum.node_pages_dir`` (default
``data/reticulum/pages/``), so an operator running ``node_enabled`` doesn't
have to SSH in to write ``index.mu``.

Deliberately narrow:
  * only ``*.mu`` files, only in the top level of the pages dir (no
    ``files/`` uploads, no subdirs) -- keeps the traversal surface nil.
  * ``info.mu`` / ``nodes.mu`` are refused: ``nomad_node.py`` generates
    those and ignores an operator file of the same name, so letting the
    editor write one would just be a file that never gets served.
  * plain files, never executable -- NomadNet runs a page as a script if
    its exec bit is set; "dynamic pages" stay an SSH-only thing on purpose.

FastAPI-free -- the route layer (``nomad_routes.py``) passes the resolved
``pages_dir`` in, and this module is what the tests exercise directly.
"""

from __future__ import annotations

import re
import time
from pathlib import Path

# Generated by nomad_node.py and served unconditionally -- an operator file
# of the same name is ignored there, so the editor refuses to create one.
RESERVED_NAMES = frozenset({"info.mu", "nodes.mu"})

# Lowercase slug + ".mu". No path separators, no leading dot, no "..".
_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9._-]{0,62}\.mu$")

# Micron is plain text; a real page is a few KB. Generous cap, still small
# enough that a runaway paste can't fill the disk.
MAX_PAGE_BYTES = 128 * 1024

# sample-pages/index.mu, shipped next to the plugin -- the "Load sample"
# button's source.
_SAMPLE_INDEX = Path(__file__).resolve().parent.parent / "sample-pages" / "index.mu"


class PageError(ValueError):
    """A bad page name or oversized content -- carries an HTTP-ready message."""


def validate_name(name: str) -> str:
    """Return *name* unchanged if it's an acceptable page filename, else
    raise :class:`PageError`."""
    if not isinstance(name, str) or not _NAME_RE.match(name) or ".." in name:
        raise PageError(
            "Page name must be lowercase letters/digits/._- ending in '.mu'.",
        )
    if name in RESERVED_NAMES:
        raise PageError(
            f"{name!r} is generated by Meshpoint and can't be edited -- "
            "link to ':/page/info.mu' from your own index.mu instead.",
        )
    return name


def _resolved(pages_dir: str | Path, name: str) -> Path:
    base = Path(pages_dir).resolve()
    target = (base / validate_name(name)).resolve()
    # Defense in depth -- _NAME_RE already blocks separators.
    if target.parent != base:
        raise PageError("Page name escapes the pages directory.")
    return target


def list_pages(pages_dir: str | Path) -> list[dict]:
    """Every editable ``*.mu`` file in the pages dir, ``index.mu`` first
    then alphabetical. ``exists``/``bytes``/``modified`` describe what's on
    disk; ``index.mu`` is always listed even when absent (it's the one an
    operator most wants to create)."""
    base = Path(pages_dir)
    on_disk = {}
    if base.is_dir():
        for p in base.glob("*.mu"):
            if p.name in RESERVED_NAMES or not _NAME_RE.match(p.name):
                continue
            st = p.stat()
            on_disk[p.name] = {
                "name": p.name, "exists": True,
                "bytes": st.st_size, "modified": int(st.st_mtime),
            }
    if "index.mu" not in on_disk:
        on_disk["index.mu"] = {
            "name": "index.mu", "exists": False, "bytes": 0, "modified": 0,
        }
    return sorted(
        on_disk.values(),
        key=lambda e: (e["name"] != "index.mu", e["name"]),
    )


def read_page(pages_dir: str | Path, name: str) -> str:
    """The file's text, or ``""`` if it doesn't exist yet."""
    target = _resolved(pages_dir, name)
    if not target.is_file():
        return ""
    return target.read_text(encoding="utf-8", errors="replace")


def write_page(pages_dir: str | Path, name: str, content: str) -> dict:
    """Create/overwrite a page. Creates the pages dir if missing. Returns
    the same shape as a :func:`list_pages` entry."""
    if not isinstance(content, str):
        raise PageError("Page content must be text.")
    encoded = content.encode("utf-8")
    if len(encoded) > MAX_PAGE_BYTES:
        raise PageError(
            f"Page is {len(encoded)} bytes; the limit is {MAX_PAGE_BYTES}.",
        )
    target = _resolved(pages_dir, name)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(encoded)
    target.chmod(0o644)  # never executable -- see module docstring
    st = target.stat()
    return {
        "name": target.name, "exists": True,
        "bytes": st.st_size, "modified": int(st.st_mtime),
    }


def delete_page(pages_dir: str | Path, name: str) -> None:
    target = _resolved(pages_dir, name)
    if target.is_file():
        target.unlink()


def sample_index() -> str:
    """The bundled ``sample-pages/index.mu`` -- the 'Load sample' button."""
    try:
        return _SAMPLE_INDEX.read_text(encoding="utf-8")
    except OSError:
        return (
            f"`c`F38f`!MESHPOINT`!`f`a\n\n"
            f"Welcome to my node.\n\n"
            f">Links\n"
            f"`[Live stats`:/page/info.mu]\n\n"
            f"# edited {time.strftime('%Y-%m-%d')}\n"
        )
