#!/usr/bin/env python3
"""Generate rnsd's own config file from local.yaml's plugins.reticulum: section.

Run as rnsd.service's own ExecStartPre, before rnsd itself starts --
this is the ONE place the RNode's serial port and radio parameters
live (plugins.reticulum.rnode_*), so rnsd needs a freshly-written config
every time those change, same as concentrator_config.py regenerates
the SX1302 HAL config from local.yaml on every meshpoint boot rather
than expecting hand edits.

Reticulum moved out of core into plugins/apps/reticulum/, so these keys
now live under plugins.reticulum.* (an opaque per-plugin dict) instead
of the old top-level reticulum: section. The plugin's own Settings tab
(GET/PUT /api/config/reticulum) edits the same keys.

Always overwrites the whole file -- like node_config.h (the Reticulum
companion firmware card's own generated file), this is a generated
artifact, not something to hand-edit alongside. Written into
plugins.reticulum.reticulum_config_dir -- the SAME directory
plugins/apps/reticulum/backend/lxmf_service.py points meshpoint's own
RNS client at.
They MUST share this directory: the shared-instance RPC channel
authenticates per-configdir (confirmed live -- meshpoint's own client
using a different configdir than rnsd produced a real, reproducible
"digest received was wrong" RPC error; see plugins/apps/reticulum/
backend/state.py + README.md for the full story), so this being the
same path is what makes the client/master split work, not just a convenience.

Lives in the plugin (its systemd unit is `plugins/apps/reticulum/rnsd.service`,
installed by `plugins/apps/reticulum/setup.sh`) so no Reticulum code is left
in core `scripts/`.

Usage (invoked by rnsd.service, WorkingDirectory=/opt/meshpoint):
    python3 plugins/apps/reticulum/write_rnsd_config.py
"""

from __future__ import annotations

import sys
from pathlib import Path

# plugins/apps/reticulum/write_rnsd_config.py -> repo root is parents[3]
sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

from src.config import load_config  # noqa: E402

_TEMPLATE = """\
# Generated by scripts/write_rnsd_config.py from local.yaml's
# plugins.reticulum: section -- do not edit manually, changes will be
# overwritten on the next rnsd.service start.

[reticulum]
  enable_transport = True
  share_instance = Yes
  instance_name = default

[logging]
  loglevel = 4

[interfaces]

  [[Default Interface]]
    type = AutoInterface
    enabled = Yes
{rnode_block}{backbone_block}"""

_RNODE_TEMPLATE = """
  [[RNode LoRa]]
    type = RNodeInterface
    enabled = Yes
    port = {rnode_serial_port}

    frequency = {rnode_frequency_hz}
    bandwidth = {rnode_bandwidth_hz}
    txpower = {rnode_tx_power}
    spreadingfactor = {rnode_spreading_factor}
    codingrate = {rnode_coding_rate}
"""

_BACKBONE_TEMPLATE = """
  [[ReticulumNet Internet]]
    type = TCPClientInterface
    enabled = Yes
    target_host = {backbone_host}
    target_port = {backbone_port}
"""


_DEFAULTS = {
    "reticulum_config_dir": "data/reticulum/rns_config",
    "rnode_enabled": True,
    "rnode_serial_port": "",
    "rnode_frequency_hz": 869_463_000,
    "rnode_bandwidth_hz": 125_000,
    "rnode_tx_power": 20,
    "rnode_spreading_factor": 8,
    "rnode_coding_rate": 5,
    "backbone_enabled": True,
    "backbone_host": "node.reticulumnet.nl",
    "backbone_port": 4242,
}


def main() -> int:
    cfg = load_config()
    raw = cfg.plugins.get("reticulum", {})
    rc = dict(_DEFAULTS)
    if isinstance(raw, dict):
        for key in _DEFAULTS:
            if raw.get(key) not in (None, ""):
                rc[key] = raw[key]
        if "rnode_serial_port" in raw:  # legitimately "" = not configured
            rc["rnode_serial_port"] = raw.get("rnode_serial_port") or ""

    config_dir = Path(rc["reticulum_config_dir"])
    config_dir.mkdir(parents=True, exist_ok=True)

    rnode_block = ""
    if not rc["rnode_enabled"]:
        print("plugins.reticulum.rnode_enabled is false -- writing a config with no RNode interface.")
    elif not rc["rnode_serial_port"]:
        print(
            "plugins.reticulum.rnode_serial_port is not set -- writing a config "
            "with no RNode interface."
        )
    else:
        rnode_block = _RNODE_TEMPLATE.format(
            rnode_serial_port=rc["rnode_serial_port"],
            rnode_frequency_hz=rc["rnode_frequency_hz"],
            rnode_bandwidth_hz=rc["rnode_bandwidth_hz"],
            rnode_tx_power=rc["rnode_tx_power"],
            rnode_spreading_factor=rc["rnode_spreading_factor"],
            rnode_coding_rate=rc["rnode_coding_rate"],
        )

    backbone_block = ""
    if not rc["backbone_enabled"]:
        print("plugins.reticulum.backbone_enabled is false -- writing a config with no TCP backbone interface.")
    else:
        backbone_block = _BACKBONE_TEMPLATE.format(
            backbone_host=rc["backbone_host"],
            backbone_port=rc["backbone_port"],
        )

    content = _TEMPLATE.format(
        rnode_block=rnode_block,
        backbone_block=backbone_block,
    )

    config_path = config_dir / "config"
    config_path.write_text(content)
    print(f"Wrote {config_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
